name: createTag

on:
  push:
    branches:
      - 'master'


jobs:
  createTag:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d-%H-%M-%N')" >> $GITHUB_OUTPUT
      - name: Create Tag
        uses: actions/github-script@v7
        with:
          # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          github-token: ${{ secrets.TOKEN_GITHUB }}
          script: |
            const {DIST_VERSION} = process.env          
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${{ steps.date.outputs.date }}`,
                sha: context.sha
            })
      
